(function(){var u=function(){var a=/\-([a-z])/g,b=function(a,b){return b.toUpperCase()};return function(d){return d.replace(a,b)}}(),m=function(a,b){var d,c,e,f,g;window.getComputedStyle?d=window.getComputedStyle(a,null).getPropertyValue(b):(d=u(b),d=a.currentStyle?a.currentStyle[d]:a.style[d]);if("cursor"===b&&(!d||"auto"===d)){c=a.tagName.toLowerCase();e=["a"];for(f=0,g=e.length;f<g;f++)if(c===e[f])return"pointer"}return d},n=function(a){if(e.prototype._singleton){a||(a=window.event);var b;this!==
window?b=this:a.target?b=a.target:a.srcElement&&(b=a.srcElement);e.prototype._singleton.setCurrent(b)}},o=function(a,b){if(a.addClass)return a.addClass(b),a;if(b&&"string"===typeof b){var d=(b||"").split(/\s+/);if(1===a.nodeType)if(a.className){for(var c=" "+a.className+" ",e=a.className,f=0,g=d.length;f<g;f++)0>c.indexOf(" "+d[f]+" ")&&(e+=" "+d[f]);a.className=e.replace(/^\s+|\s+$/g,"")}else a.className=b}return a},k=function(a,b){if(a.removeClass)return a.removeClass(b),a;if(b&&"string"===typeof b||
void 0===b){var d=(b||"").split(/\s+/);if(1===a.nodeType&&a.className)if(b){for(var c=(" "+a.className+" ").replace(/[\n\t]/g," "),e=0,f=d.length;e<f;e++)c=c.replace(" "+d[e]+" "," ");a.className=c.replace(/^\s+|\s+$/g,"")}else a.className=""}return a},p=function(a){return e.prototype._singleton.options.useNoCache?(0<=a.indexOf("?")?"&nocache=":"?nocache=")+(new Date).getTime():""},q=function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,c=b.length;d<c;d++)if(b[d]===a)return d;return-1},r=function(a){if("string"===
typeof a)throw new TypeError("ZeroClipboard doesn't accept query strings.");return!a.length?[a]:a},v=function(a,b,d,c,e){e?window.setTimeout(function(){a.call(b,d,c)},0):a.call(b,d,c)},e=function(a,b){a&&(e.prototype._singleton||this).glue(a);if(e.prototype._singleton)return e.prototype._singleton;e.prototype._singleton=this;this.options={};for(var d in l)this.options[d]=l[d];for(var c in b)this.options[c]=b[c];this.handlers={};if(e.detectFlashSupport()){d=e.prototype._singleton;c=document.getElementById("global-zeroclipboard-html-bridge");
if(!c){c={};for(var h in d.options)c[h]=d.options[h];c.amdModuleId=s;c.cjsModuleId=t;var f;h=[];c.trustedDomains&&("string"===typeof c.trustedDomains&&c.trustedDomains?f=[c.trustedDomains]:"length"in c.trustedDomains&&(f=c.trustedDomains),h.push("trustedDomain="+encodeURIComponent(f.join(","))));"string"===typeof c.amdModuleId&&c.amdModuleId&&h.push("amdModuleId="+encodeURIComponent(c.amdModuleId));"string"===typeof c.cjsModuleId&&c.cjsModuleId&&h.push("cjsModuleId="+encodeURIComponent(c.cjsModuleId));
f=h.join("&");f='      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="global-zeroclipboard-flash-bridge" width="100%" height="100%">         <param name="movie" value="'+d.options.moviePath+p(d.options.moviePath)+'"/>         <param name="allowScriptAccess" value="'+d.options.allowScriptAccess+'"/>         <param name="scale" value="exactfit"/>         <param name="loop" value="false"/>         <param name="menu" value="false"/>         <param name="quality" value="best" />         <param name="bgcolor" value="#ffffff"/>         <param name="wmode" value="transparent"/>         <param name="flashvars" value="'+
f+'"/>         <embed src="'+d.options.moviePath+p(d.options.moviePath)+'"           loop="false" menu="false"           quality="best" bgcolor="#ffffff"           width="100%" height="100%"           name="global-zeroclipboard-flash-bridge"           allowScriptAccess="always"           allowFullScreen="false"           type="application/x-shockwave-flash"           wmode="transparent"           pluginspage="http://www.macromedia.com/go/getflashplayer"           flashvars="'+f+'"           scale="exactfit">         </embed>       </object>';
c=document.createElement("div");c.id="global-zeroclipboard-html-bridge";c.setAttribute("class","global-zeroclipboard-container");c.setAttribute("data-clipboard-ready",!1);c.style.position="absolute";c.style.left="-9999px";c.style.top="-9999px";c.style.width="15px";c.style.height="15px";c.style.zIndex="9999";c.innerHTML=f;document.body.appendChild(c)}d.htmlBridge=c;d.flashBridge=document["global-zeroclipboard-flash-bridge"]||c.children[0].lastElementChild}},i,j=[];e.prototype.setCurrent=function(a){i=
a;this.reposition();var b=a.getAttribute("title");b&&this.setTitle(b);a=!0===this.options.forceHandCursor||"pointer"===m(a,"cursor");this.ready()&&this.flashBridge.setHandCursor(a)};e.prototype.setText=function(a){a&&""!==a&&(this.options.text=a,this.ready()&&this.flashBridge.setText(a))};e.prototype.setTitle=function(a){a&&""!==a&&this.htmlBridge.setAttribute("title",a)};e.prototype.setSize=function(a,b){this.ready()&&this.flashBridge.setSize(a,b)};e.prototype.setHandCursor=function(a){var b=a="boolean"===
typeof a?a:!!a;this.ready()&&this.flashBridge.setHandCursor(b);this.options.forceHandCursor=a};e.version="1.2.0-beta.4";var l={moviePath:"ZeroClipboard.swf",trustedDomains:null,text:null,hoverClass:"zeroclipboard-is-hover",activeClass:"zeroclipboard-is-active",allowScriptAccess:"sameDomain",useNoCache:!0,forceHandCursor:!1};e.setDefaults=function(a){for(var b in a)l[b]=a[b]};e.destroy=function(){e.prototype._singleton.unglue(j);var a=e.prototype._singleton.htmlBridge;a.parentNode.removeChild(a);delete e.prototype._singleton};
e.detectFlashSupport=function(){var a=!1;if("function"===typeof ActiveXObject)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash")&&(a=!0)}catch(b){}!a&&navigator.mimeTypes["application/x-shockwave-flash"]&&(a=!0);return a};var s=null,t=null;e.prototype.resetBridge=function(){this.htmlBridge.style.left="-9999px";this.htmlBridge.style.top="-9999px";this.htmlBridge.removeAttribute("title");this.htmlBridge.removeAttribute("data-clipboard-text");k(i,this.options.activeClass);i=null;this.options.text=
null};e.prototype.ready=function(){var a=this.htmlBridge.getAttribute("data-clipboard-ready");return"true"===a||!0===a};e.prototype.reposition=function(){if(!i)return!1;var a=i,b=0,d=0,c=0,e=0,f=999999999,g=m(a,"z-index");g&&"auto"!==g&&(f=parseInt(g,10));a.getBoundingClientRect&&(a=a.getBoundingClientRect(),"pageXOffset"in window&&"pageYOffset"in window?(b=window.pageXOffset,d=window.pageYOffset):(b=1,"function"===typeof document.body.getBoundingClientRect&&(b=document.body.getBoundingClientRect(),
b=b.right-b.left,d=document.body.offsetWidth,b=Math.round(100*(b/d))/100),d=b,b=Math.round(document.documentElement.scrollLeft/d),d=Math.round(document.documentElement.scrollTop/d)),c=document.documentElement.clientTop||0,b=a.left+b-(document.documentElement.clientLeft||0),d=a.top+d-c,c="width"in a?a.width:a.right-a.left,e="height"in a?a.height:a.bottom-a.top);this.htmlBridge.style.top=d+"px";this.htmlBridge.style.left=b+"px";this.htmlBridge.style.width=c+"px";this.htmlBridge.style.height=e+"px";
this.htmlBridge.style.zIndex=f+1;this.setSize(c,e)};e.dispatch=function(a,b){e.prototype._singleton.receiveEvent(a,b)};e.prototype.on=function(a,b){for(var d=a.toString().split(/\s/g),c=0;c<d.length;c++)a=d[c].toLowerCase().replace(/^on/,""),this.handlers[a]||(this.handlers[a]=b);this.handlers.noflash&&!e.detectFlashSupport()&&this.receiveEvent("onNoFlash",null)};e.prototype.addEventListener=e.prototype.on;e.prototype.off=function(a,b){for(var d=a.toString().split(/\s/g),c=0;c<d.length;c++){var a=
d[c].toLowerCase().replace(/^on/,""),e;for(e in this.handlers)e===a&&this.handlers[e]===b&&delete this.handlers[e]}};e.prototype.removeEventListener=e.prototype.off;e.prototype.receiveEvent=function(a,b){var a=a.toString().toLowerCase().replace(/^on/,""),d=i,c=!0;switch(a){case "load":if(b&&10>parseFloat(b.flashVersion.replace(",",".").replace(/[^0-9\.]/gi,""))){this.receiveEvent("onWrongFlash",{flashVersion:b.flashVersion});return}this.htmlBridge.setAttribute("data-clipboard-ready",!0);break;case "mouseover":o(d,
this.options.hoverClass);break;case "mouseout":k(d,this.options.hoverClass);this.resetBridge();break;case "mousedown":o(d,this.options.activeClass);break;case "mouseup":k(d,this.options.activeClass);break;case "datarequested":c=d.getAttribute("data-clipboard-target");(c=(c=!c?null:document.getElementById(c))?c.value||c.textContent||c.innerText:d.getAttribute("data-clipboard-text"))&&this.setText(c);c=!1;break;case "complete":this.options.text=null}if(this.handlers[a]){var e=this.handlers[a];"string"===
typeof e&&"function"===typeof window[e]&&(e=window[e]);"function"===typeof e&&v(e,d,this,b,c)}};e.prototype.glue=function(a){for(var a=r(a),b=0;b<a.length;b++)if(-1==q(a[b],j)){j.push(a[b]);var d=a[b],c=n;d.addEventListener?d.addEventListener("mouseover",c,!1):d.attachEvent&&d.attachEvent("onmouseover",c)}};e.prototype.unglue=function(a){for(var a=r(a),b=0;b<a.length;b++){var d=a[b],c=n;d.removeEventListener?d.removeEventListener("mouseover",c,!1):d.detachEvent&&d.detachEvent("onmouseover",c);d=q(a[b],
j);-1!=d&&j.splice(d,1)}};"function"===typeof define&&define.amd?define(["require","exports","module"],function(a,b,d){s=d&&d.id||null;return e}):"undefined"!==typeof module&&module?(t=module.id||null,module.exports=e):window.ZeroClipboard=e})();
//@ sourceMappingURL=ZeroClipboard.js.map